Bug Tracker/Models/UserRoles.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bug_Tracker.Models
{
    public class UserRoles
    {
        public List<ApplicationUser> Users { get; set; }
        public List<ApplicationUser> Submitters { get; set; }
        public List<ApplicationUser> Developers { get; set; }
        public List<ApplicationUser> ProjectManagers { get; set; }
        public List<ApplicationUser> Admins { get; set; }
    }
}

Bug Tracker/Models/UserRolesHelper.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Bug_Tracker.Models
{
    public class UserRolesHelper
    {
        private ApplicationDbContext db;
        private UserManager<ApplicationUser> userManager;
        private RoleManager<IdentityRole> roleManager;
        
        public UserRolesHelper(ApplicationDbContext context)
        {
            this.userManager = new UserManager<ApplicationUser>(
                new UserStore<ApplicationUser>(context));
            this.roleManager = new RoleManager<IdentityRole>(
         new RoleStore<IdentityRole>(context));
            this.db = context;
        }

        public bool IsUserInRole(string userId, string roleName)
        {
            return userManager.IsInRole(userId, roleName);
        }

        public IList<string> ListUserRoles(string userId)
        {
            return userManager.GetRoles(userId);
        }

        public bool AddUserToRole(string userId, string roleName)
        {
            var result = userManager.AddToRole(userId, roleName);
            return result.Succeeded;
        }

        public bool RemoveUserFromRole(string userId, string roleName)
        {
            var result = userManager.RemoveFromRole(userId, roleName);
            return result.Succeeded;
        }

        public ICollection<UserDropDownViewModel> UsersInRole(string roleName)
        {
            var userIDs = roleManager.FindByName(roleName).Users.Select(r => r.UserId);
            var model = new List<UserDropDownViewModel>();
            var users = userManager.Users.Where(u => userIDs.Contains(u.Id));
            foreach(var u in users)
            {
                model.Add(new UserDropDownViewModel {Id = u.Id, UserName = u.UserName});
            }
            return model;
            //var userIDs = roleManager.FindByName(roleName).Users.Select(r => r.UserId);
            //return userManager.Users.Where(u => userIDs.Contains(u.Id)).Select(u =>
            //    new UserDropDownViewModel {Id = u.Id, UserName = u.UserName}).ToList();
        }

        //public IList<string> ListDevelopersOnProject(string userId)
        //{
        //    Project project = new Project();
        //    var projectId = project.Id;
        //    var developers = UsersInRole("Developer");
        //    var developersOnProject = developers.Where(x => x.Id == project.);
        //    return userManager.GetRoles(userId);
        //}
    }
}

Bug Tracker/Models/UserRolesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;

namespace Bug_Tracker.Models
{
    public class UserRolesViewModel
    {
        public List<ApplicationUser> AllUsers { get; set; }
        public string RoleId { get; set; }
        [Display(Name = "Role Name")]
        public string RoleName { get; set; }
        [Display(Name = "Assigned Users")]
        public System.Web.Mvc.MultiSelectList Users { get; set; }
        public string[] SelectedUsers { get; set; }
        //public ICollection<UserDropDownViewModel> Submitters { get; set; }
        //public List<ApplicationUser> Developers { get; set; }
        //public List<ApplicationUser> ProjectManagers { get; set; }
        //public List<ApplicationUser> Admins { get; set; }
    }

    public class RolesViewModel
    {
        public string RoleId { get; set; }
        public string RoleName { get; set; }
    }
}

Bug Tracker/Controllers/UserRolesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bug_Tracker.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Bug_Tracker.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserRolesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserRolesHelper rolesHelper;

        public UserRolesController()
        {
            this.rolesHelper = new UserRolesHelper(db);    
        }

        // GET: UserRoles
        public ActionResult Index()
        {
            var roles = db.Roles.ToList();
            List<RolesViewModel> model = new List<RolesViewModel>();
            foreach (var r in roles)
            {
                model.Add(new RolesViewModel { RoleId = r.Id, RoleName = r.Name });
            }
            return View(model);
        }

        // Get: UserRoles/Edit
        public ActionResult EditUserRoles(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }

            var model = new UserRolesViewModel();
            model.RoleId = id;
            model.RoleName = role.Name;
            model.SelectedUsers = role.Users.Select(u => u.UserId).ToArray();
            var availableUsers = db.Users;
            model.Users = new MultiSelectList(availableUsers, "Id", "UserName", null);

            return View(model);
        }

        // POST: UserRoles/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUserRoles([Bind(Include = "RoleId, RoleName, SelectedUsers")] UserRolesViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = db.Roles.Find(model.RoleId);
                var users = rolesHelper.UsersInRole(role.Name);
                // remove unselected users
                foreach (var u in users)
                {
                    if (!model.SelectedUsers.Contains(u.Id))
                    {
                        rolesHelper.RemoveUserFromRole(u.Id, role.Name);
                    }
                }
                //add newly selected users
                foreach (var id in model.SelectedUsers)
                {
                    if (!rolesHelper.IsUserInRole(id, role.Name))
                    {
                        rolesHelper.AddUserToRole(id, role.Name);
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

Bug Tracker/Views/UserRoles/EditUserRoles.cshtml
@model Bug_Tracker.Models.UserRolesViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>

            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                    <li>
                        <span>Role Management</span>
                    </li>
                    <li class="active">
                        <span>@Model.RoleName</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                <i class="pe-7s-id"></i>   Add or Remove Users From: @Model.RoleName  
            </h2>
        </div>
    </div>
</div>

<div class="content animate-panel">

    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        <a class="closebox"><i class="fa fa-times"></i></a>
                    </div>
                    <h3>@Model.RoleName (s)</h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="tableExample2" class="table">
                            @using (Html.BeginForm())
                            {
                                @Html.HiddenFor(model => model.RoleId)
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.Label("Assigned Users", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <small>Control + Click To Select Multiple Users</small>
                                    <div calss="col-md-10">
                                        @Html.ListBoxFor(model => model.SelectedUsers, Model.Users, new { @class = "form-control", size = 10 })
                                        @Html.ValidationMessageFor(model => model.SelectedUsers, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Submit Changes" class="btn btn-w-md btn-primary" />
                                    </div>
                                </div>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Bug Tracker/Views/UserRoles/EditUserRoles1.cshtml
@*@model Bug_Tracker.Models.UserRolesViewModel
@{
    ViewBag.Title = "EditUserRoles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.)

        <div class="form-group">
            @Html.LabelFor(model => model., htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedProjectManagerId, Model.ProjectManagers, "--Select Project Manager--", new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.SelectedProjectManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Assigned Developers", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.SelectedDevelopers, Model.Developers, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectedDevelopers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Users Dashboard", "Index")
</div>*@

Bug Tracker/Views/UserRoles/Index.cshtml
@using Bug_Tracker.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<Bug_Tracker.Models.RolesViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>

            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                    <li>
                        <span>Role Management</span>
                    </li>
                    <li class="active">
                        <span>Role Management</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                <i class="pe-7s-id"></i>  Role Management
            </h2>
        </div>
    </div>
</div>

<div class="content animate-panel">

    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        <a class="closebox"><i class="fa fa-times"></i></a>
                    </div>
                    <h3>Roles</h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="tableExample2" class="table">

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <h4>
                                        @item.RoleName
                                        </h4>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("EditUserRoles", "UserRoles", new {id = item.RoleId})" alt="View Role">
                                            <i class="fa fa-edit accentcolor-heading fa-2x"></i>
                                        </a>
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/bundles/datatables/css")
}

@section Scripts {
    @Scripts.Render("~/bundles/datatables/js")
    @Scripts.Render("~/bundles/datatablesBootstrap/js")
    @Scripts.Render("~/bundles/datatablesPlugins/js")

    <script type="text/javascript">

        $(function () {
            // Initialize Example 2
            $('#example2').dataTable();

        });

    </script>
}

Bug Tracker/Views/UserRoles/Index1.cshtml
@using Bug_Tracker.Models
@using Microsoft.AspNet.Identity
@model Bug_Tracker.Models.UserRolesViewModel
@{
    ViewBag.Title = "Contact";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900' rel='stylesheet' type='text/css'>
    <!-- Page title -->
    <title>LUNA | Responsive Admin Theme</title>
    <!-- Vendor styles -->
    <link rel="stylesheet" href="~/vendor/fontawesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/vendor/animate.css/animate.css" />
    <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/vendor/datatables/datatables.min.css" />
    <!-- App styles -->
    <link rel="stylesheet" href="~/styles/pe-icons/pe-icon-7-stroke.css" />
    <link rel="stylesheet" href="~/styles/pe-icons/helper.css" />
    <link rel="stylesheet" href="~/styles/stroke-icons/style.css" />
    <link rel="stylesheet" href="~/styles/style.css">
</head>
<body>
    <!-- Wrapper-->
        <!-- Main content-->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="view-header">
                            <div class="pull-right text-right" style="line-height: 14px">
                                <small>Table design<br>General<br> <span class="c-white">DataTables</span></small>
                            </div>
                            <div class="header-icon">
                                <i class="pe page-header-icon pe-7s-albums"></i>
                            </div>
                            <div class="header-title">
                                <h3>Role Management</h3>
                                <small>
                                    Administrator Role Management Page
                                </small>
                            </div>
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-filled">
                            <div class="panel-heading">
                                <div class="panel-tools">
                                    <a class="panel-toggle"><i class="fa fa-chevron-up"></i></a>
                                    <a class="panel-close"><i class="fa fa-times"></i></a>
                                </div>
                               Users
                            </div>
                            <div class="panel-body">
                                <p>
                                    The Buttons library for DataTables provides a framework with common options and API that can be used with DataTables, but is also very extensible, recognising that you will likely want to use buttons which perform an action unique to your applications.
                                </p>
                                <div class="table-responsive">
                                    
                                    <table id="tableExample2" class="table table-striped table-hover">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Username</th>
                                            <th>Current Role</th>
                                            <th>Email</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach (var user in Model.AllUsers)
                                        {
                                            <tr>
                                                <td>@user.UserName</td>
                                                @*<td>@user.</td>
                                                <td>@user.</td>
                                                <td>@user.</td>*@
                                                <td>@Html.ActionLink("Change Role", "EditUserRoles", "UserRoles", new {id = user.Id})</td>
                                                <td></td>
                                            </tr>
                                        }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        <!-- End main content-->
    <!-- End wrapper-->
    <!-- Vendor scripts -->
    <script src="~/vendor/pacejs/pace.min.js"></script>
    <script src="~/vendor/jquery/dist/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/vendor/datatables/datatables.min.js"></script>
    <!-- App scripts -->
    <script src="~/scripts/luna.js"></script>

    <script>
    $(document).ready(function () {

        $('#tableExample1').DataTable({
            "dom": 't'
        });

        $('#tableExample2').DataTable({
            "dom": "<'row'<'col-sm-6'l><'col-sm-6'f>>t<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "lengthMenu": [ [6, 25, 50, -1], [6, 25, 50, "All"] ],
            "iDisplayLength": 6,
        });

        $('#tableExample3').DataTable({
            dom: "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>tp",
            "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ],
            buttons: [
                {extend: 'copy',className: 'btn-sm'},
                {extend: 'csv',title: 'ExampleFile', className: 'btn-sm'},
                {extend: 'pdf', title: 'ExampleFile', className: 'btn-sm'},
                {extend: 'print',className: 'btn-sm'}
            ]
        });

    });
    </script>
</body>
</html>

Bug Tracker/Views/UserRoles/Index3.cshtml
@using Bug_Tracker.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<Bug_Tracker.Models.RolesViewModel>
@{
    ViewBag.Title = "Contact";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900' rel='stylesheet' type='text/css'>
    <!-- Page title -->
    <title>LUNA | Responsive Admin Theme</title>
    <!-- Vendor styles -->
    <link rel="stylesheet" href="~/vendor/fontawesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/vendor/animate.css/animate.css" />
    <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/vendor/datatables/datatables.min.css" />
    <!-- App styles -->
    <link rel="stylesheet" href="~/styles/pe-icons/pe-icon-7-stroke.css" />
    <link rel="stylesheet" href="~/styles/pe-icons/helper.css" />
    <link rel="stylesheet" href="~/styles/stroke-icons/style.css" />
    <link rel="stylesheet" href="~/styles/style.css">
</head>
<body>
    <!-- Wrapper-->
        <!-- Main content-->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="view-header">
                            <div class="pull-right text-right" style="line-height: 14px">
                                <small>Table design<br>General<br> <span class="c-white">DataTables</span></small>
                            </div>
                            <div class="header-icon">
                                <i class="pe page-header-icon pe-7s-albums"></i>
                            </div>
                            <div class="header-title">
                                <h3>Role Management</h3>
                                <small>
                                    Administrator Role Management Page
                                </small>
                            </div>
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-filled">
                            <div class="panel-heading">
                                <div class="panel-tools">
                                    <a class="panel-toggle"><i class="fa fa-chevron-up"></i></a>
                                    <a class="panel-close"><i class="fa fa-times"></i></a>
                                </div>
                               Users
                            </div>
                            <div class="panel-body">
                                <p>
                                    The Buttons library for DataTables provides a framework with common options and API that can be used with DataTables, but is also very extensible, recognising that you will likely want to use buttons which perform an action unique to your applications.
                                </p>
                                <div class="table-responsive">
                                    
                                    <table id="tableExample2" class="table table-striped table-hover">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Username</th>
                                            <th>Current Role</th>
                                            <th>Email</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {
                                            <tr>
                                                <td>fdsfsdfdf</td>
                                                <td>hdfggfgfg</td>
                                                <td>fdfgdfdg</td>
                                                <td>gdgfdg</td>
                                                <td></td>
                                            </tr>
                                        }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        <!-- End main content-->
    <!-- End wrapper-->
    <!-- Vendor scripts -->
    <script src="~/vendor/pacejs/pace.min.js"></script>
    <script src="~/vendor/jquery/dist/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/vendor/datatables/datatables.min.js"></script>
    <!-- App scripts -->
    <script src="~/scripts/luna.js"></script>

    <script>
    $(document).ready(function () {

        $('#tableExample1').DataTable({
            "dom": 't'
        });

        $('#tableExample2').DataTable({
            "dom": "<'row'<'col-sm-6'l><'col-sm-6'f>>t<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "lengthMenu": [ [6, 25, 50, -1], [6, 25, 50, "All"] ],
            "iDisplayLength": 6,
        });

        $('#tableExample3').DataTable({
            dom: "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>tp",
            "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ],
            buttons: [
                {extend: 'copy',className: 'btn-sm'},
                {extend: 'csv',title: 'ExampleFile', className: 'btn-sm'},
                {extend: 'pdf', title: 'ExampleFile', className: 'btn-sm'},
                {extend: 'print',className: 'btn-sm'}
            ]
        });

    });
    </script>
</body>
</html>